### ISSUE TITLE
MVA更新计划

### ISSUE THREAD

**Issue by mic12130** [VATPRC-Sector/Sector#1]
AIP中公布了MVA的机场：

- [x] ZBSJ
- [x] ZGGG
- [x] ZGHA
- [x] ZGNN
- [x] ZGOW
- [x] ZHCC
- [x] ZHHH
- [x] ZJHK
- [x] ZJSY
- [x] ZLXN
- [x] ZLXY
- [x] ZPLJ
- [x] ZPPP
- [x] ZSAM
- [x] ZSCN
- [x] ZSJN
- [x] ZSOF
- [x] ZSSS
- [x] ZUCK
- [x] ZUGY
- [x] ZUUU
- [x] ZWWW

打勾的为扇区中制作了MVA的机场

**Comment by XCSWxcsw** [comment]
已全部更新完成，无问题后就可以关了
