### ISSUE TITLE
大连地面扇区大幅度调整

### ISSUE THREAD

**Issue by mic12130** [VATPRC-Sector/Sector#111]
**Description**

地景已更新且已确认坐标正确，因此现在可以对大连地面扇区进行调整。

调整的范围主要有：
- 修正整体坐标偏移
- 新增E快速脱离道
- 新增停机位
- 调整东侧机坪。

取代 #9 和 #73 

**Screenshots**

**Comment by mic12130** [comment]
等待地景更新（FSX/P3D和XP）。

**Comment by mic12130** [comment]
地景已更新：http://forum.vatprc.net/index.php?/topic/2283-180915%E6%9B%B4%E6%96%B0fsxp3dzytl%E5%A4%A7%E8%BF%9E%E5%91%A8%E6%B0%B4%E5%AD%90%E5%9B%BD%E9%99%85%E6%9C%BA%E5%9C%BA-sinovatprc/#entry18113

**Comment by XCSWxcsw** [comment]
另有A北移 另建议下一期等我地景更新后再更新 由于下一期机位开放 E 开放 28内移

**Comment by mic12130** [comment]
@XCSWxcsw 请在地景更新后在此issue内告知，谢谢

**Comment by XCSWxcsw** [comment]
@mic12130 已更新
[181007更新][FSX/P3D]ZYTL大连周水子国际机场 [SINO,VATPRC]
https://bbs.sinofsx.com/forum.php?mod=viewthread&tid=168596
http://forum.vatprc.net/index.php?/topic/2283-181007%E6%9B%B4%E6%96%B0fsxp3dzytl%E5%A4%A7%E8%BF%9E%E5%91%A8%E6%B0%B4%E5%AD%90%E5%9B%BD%E9%99%85%E6%9C%BA%E5%9C%BA-sinovatprc/?p=16397
2018.10.06更新：
1、E滑行道开放。
2、跑道28内移300米。
3、跑道28盲降加装DME。
4、中指点和外指点,位置更新。
5、空军指挥楼拆除。

**Comment by mic12130** [comment]
@XCSWxcsw thx
