### ISSUE TITLE
请求对语音AITS进行扩充

### ISSUE THREAD

**Issue by XCSWxcsw** [VATPRC-Sector/Sector#154]
很多拥有语音ATIS的机场没有机场的语音文件。如大连、沈阳、长沙等。建议添加在发布版本中。

ES国内主要机场ATIS声音文件：（可选用）
http://forum.vatprc.net/index.php?/topic/294-es%E5%9B%BD%E5%86%85%E4%B8%BB%E8%A6%81%E6%9C%BA%E5%9C%BAatis%E5%A3%B0%E9%9F%B3%E6%96%87%E4%BB%B6/

**Comment by mic12130** [comment]
计划在未来更新AIP中所有机场的ATIS音频文件。
由于目前的重点主要在于更新扇区基础数据和地面扇区，因此先搁置本issue。
