### ISSUE TITLE
建议将Login Profiles更方便

### ISSUE THREAD

**Issue by XCSWxcsw** [VATPRC-Sector/Sector#197]
建议将Login Profiles中的ATIS2（呼号）改为各席位的呼号，如：

PROFILE:ZBAA_TWR:50:4
ATIS2:Callsign ***
ATIS3:China RVSM in use
ATIS4:For charts and more info please visit www.vatprc.net

更改为

PROFILE:ZBAA_TWR:50:4
ATIS2:Callsign **Beijing Tower**
ATIS3:China RVSM in use
ATIS4:For charts and more info please visit www.vatprc.net

这样在ATC登陆时可以更加快捷，防止因忘记而产生的遗漏。

**Comment by mic12130** [comment]
无法实现从席位（如 ZBAA_TWR）到呼号（如 Beijing Tower）的映射
