### ISSUE TITLE
石家庄进近管制区边界错误

### ISSUE THREAD

**Issue by XCSWxcsw** [VATPRC-Sector/Sector#77]
![image](https://user-images.githubusercontent.com/40914896/85407623-b74eb580-b563-11ea-99a0-c71dd8354799.png)
![image](https://user-images.githubusercontent.com/40914896/85408756-3abcd680-b565-11ea-91c8-b3d7883b2aec.png)

**Comment by mic12130** [comment]
MVA也需要相应地更新（#1）
